name: publish npm package

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: 'some_dummy_token'
          dry-run: true
      - if: ${{ steps.publish.outputs.type }}
        run: echo "Version changed!"
